services:
  - type: web
    name: github-receipt-backend
    env: node
    buildCommand: |
      cd server && 
      npm install && 
      npm run build &&
      ls -la dist
    startCommand: cd server && node dist/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: GITHUB_TOKEN
        sync: false
    healthCheckPath: /api/health
